const clothStyleEnums = [
  "T-Shirt",
  "Trousers",
  "African Traditional",
  "Midaxi Skirt",
  "Chinos",
  "Jumper",
  "Bicker Jacket",
  "Pyjama",
  "Pant",
  "Baby Tee",
  "Tracksuit",
  "Corset",
  "Tights",
  "Trunks",
  "PullOver",
  "Vintage",
  "Tank-Top",
  "Shirt",
  "Skirt",
  "Mini Skirt",
  "Maxi Skirt",
  "Waistcoat",
  "BodySuit",
  "Jeans",
  "Crop-Top",
  "Tube-Top",
  "Peplum",
  "Tunic",
  "Blouse",
  "Sweater",
  "Cardigan",
  "Vest",
  "Jacket",
  "Coat",
  "Poncho",
  "Cape",
  "Kimono",
  "Kaftan",
  "Work",
  "Street",
  "Sweatshirt",
  "Pullover",
  "Polo",
  "Turtleneck",
  "Halter",
  "Jean",
  "Bralet",
  "Hoodie",
  "Oversized T-shirt",
  "Top & Skirt",
  "Top & Trouser",
  "2-in-1 Shorts",
  "Top & Shorts",
  "Top & Jacket",
  "Hot Pant",
  "Jumper Dress",
  "Jumpsuit",
  "Gilet",
  "Playsuit",
  "Romper",
  "Dungaree",
  "Overalls",
  "Coveralls",
  "Thong",
  "Nightie",
  "Knicker",
  "Boiler Suit",
  "Catsuit",
  "Unitard",
  "Leotard",
  "Bodysuit",
  "Swimsuit",
  "Bikini",
  "Monokini",
  "Tankini",
  "Trikini",
  "Burkini",
  "Wetsuit",
  "Rash Guard",
  "Surf Suit",
  "Drysuit",
  "leggings",
  "Bodycon Dress",
  "Flares",
  "Shift Dress",
  "Corset Dress",
  "Shirt Dress",
  "Blazer Dress",
  "A-line Dress",
  "Slip Dress",
  "Jumper Dress",
  "Dress",
  "Oversized Jumper Dress",
  "Lingerie",
  "Two Piece",
  "Three Piece",
  "Wide Leg Trousers",
  "Other",
];
const sleeveLengthEnums = [
  "Long Sleeve",
  "Short Sleeve",
  "Sleeveless",
  "Off Shoulder",
  "Strapless",
  "Spaghetti",
  "Cap Sleeve",
  "Puff Sleeve",
  "Bishop Sleeve",
  "Bell Sleeve",
  "Kimono Sleeve",
  "Dolman Sleeve",
  "Raglan Sleeve",
  "Batwing Sleeve",
  "Butterfly Sleeve",
  "Cold Shoulder",
  "One Shoulder",
  "Asymmetric",
  "Cape Sleeve",
  "Flounce Sleeve",
  "Ruffle Sleeve",
  "Tiered Sleeve",
];
const designEnums = [
  "Plain",
  "Faux Fur",
  "Ripped",
  "Buba",
  "Leather",
  "Patterned",
  "Printed",
  "Embroidered",
  "Sequined",
  "Lace",
  "Mesh",
  "Sheer",
  "Cut-Out",
  "Ruched",
  "Ruffled",
  "Tiered",
  "Pleated",
  "Frill",
  "Flounce",
  "Tie-Dye",
  "Tie-Front",
  "Wrap",
  "Twist",
  "Knot",
  "Bow",
  "Belted",
  "Buckle",
  "Buttoned",
  "Zipper",
  "Lace-Up",
  "Corset",
  "Peplum",
  "Puff",
  "Balloon",
  "Bubble",
  "Animal",
  "Leopard",
  "Check",
  "Plaid",
  "Tartan",
  "Striped",
  "Floral",
  "Tropical",
  "Paisley",
  "Geometric",
  "Abstract",
  "Aztec",
  "Tribal",
  "Camouflage",
  "Marble",
];
const fasteningEnums = [
  "Button",
  "Zipper",
  "Hook",
  "Tie",
  "Buckle",
  "Lace-Up",
  "Corset",
  "Cord",
  "Snap",
  "Velcro",
  "Elastic",
  "Drawstring",
  "Belt",
  "Sash",
  "Buckle",
  "Clasp",
  "Magnet",
  "Press-Stud",
  "Toggle",
  "D-Ring",
  "Buckle",
  "Braid",
  "Frog",
  "Grommet",
  "Knot",
  "Loop",
  "Pleat",
  "Ribbon",
  "Rope",
  "Ruffle",
  "Tassel",
  "Twist",
  "Wrap",
  "None",
];
const fabricEnums = [
  "Cotton",
  "Polyester",
  "Nylon",
  "Spandex",
  "Rayon",
  "Linen",
  "Silk",
  "Wool",
  "Cashmere",
  "Leather",
  "Fur",
  "Faux Fur",
  "Denim",
  "Velvet",
  "Satin",
  "Chiffon",
  "Lace",
  "Mesh",
  "Sheer",
  "Tulle",
  "Knit",
  "Jersey",
  "Terry",
  "Fleece",
  "Flannel",
  "Tweed",
  "Corduroy",
  "Suede",
  "Sequin",
  "Glitter",
  "Metallic",
  "Lurex",
  "Lamé",
  "Brocade",
  "Jacquard",
  "Damask",
  "Taffeta",
];
const colorEnums = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Red", hex: "#FF0000" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Blue", hex: "#0000FF" },
  { name: "Green", hex: "#008000" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "Purple", hex: "#800080" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Grey", hex: "#808080" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Navy", hex: "#000080" },
  { name: "Teal", hex: "#008080" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Mint", hex: "#98FF98" },
  { name: "Lime", hex: "#00FF00" },
  { name: "Olive", hex: "#808000" },
  { name: "Khaki", hex: "#F0E68C" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Bronze", hex: "#CD7F32" },
  { name: "Copper", hex: "#B87333" },
  { name: "Rose Gold", hex: "#B76E79" },
  { name: "Metallic", hex: "#D3AF37" },
  { name: "Neon", hex: "#39FF14" },
  { name: "Pastel", hex: "#FF6961" },
  { name: "Rainbow", hex: "#FF0000" },
  {
    name: "Multicolor",
    background:
      "radial-gradient(circle, hsla(41, 83%, 70%, 1) 23%, hsla(321, 90%, 70%, 1) 100%)",
  },
  { name: "Lilac", hex: "#C8A2C8" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Wine", hex: "#722F37" },
  { name: "Chocolate", hex: "#D2691E" },
  { name: "Milk", hex: "#F5F5DC" },
];
const mainEnums = [
  "Top",
  "Bottom",
  "Dress",
  "Matching Set",
  "Footwear",
  "Overall",
  "Two Piece",
  "Three Piece",
  "Accessories",
  "Other",
];
const occasionEnums = [
  "Casual",
  "Formal",
  "Wedding",
  "Bridal",
  "Bridesmaid",
  "Maternity",
  "Cocktail",
  "Beach",
  "Summer",
  "Winter",
  "Spring",
  "Autumn",
  "Fall",
  "Retro",
  "Boho",
  "Chic",
  "Sexy",
  "Party",
  "Evening",
  "Day",
  "Work",
  "Office",
  "Business",
  "Corporate",
  "Smart Casual",
  "Dressy",
  "Festive",
  "Holiday",
  "Vacation",
  "Date",
  "Funeral",
  "Travel",
  "Resort",
  "Cruise",
  "Camping",
  "Hiking",
  "Outdoor",
  "Gym",
  "Athletic",
  "Sports",
  "Fitness",
  "Yoga",
  "Pilates",
  "Dance",
  "Ballet",
  "Gymnastics",
  "Running",
  "Jogging",
  "Walking",
  "Cycling",
  "Swimming",
  "Surfing",
  "Skiing",
  "Snowboarding",
  "Skating",
  "Skateboarding",
  "Scootering",
  "Horse Riding",
  "Sports",
];
const fitEnums = [
  "Regular",
  "Slim",
  "Skinny",
  "Straight",
  "Bootcut",
  "Flare",
  "Wide-Leg",
  "Cropped",
  "Culotte",
  "Palazzo",
  "Paperbag",
  "Pegged",
  "Tapered",
  "Carrot",
  "Boyfriend",
  "Mom",
  "Dad",
  "High-Waist",
  "Low-Waist",
  "Mid-Waist",
  "Drop-Waist",
  "Plus-Size",
  "Petite",
  "Maternity",
  "Tall",
  "Short",
  "Long",
  "Regular",
  "Oversized",
  "Fitted",
  "Relaxed",
  "Baggy",
  "Slouchy",
  "Boxy",
  "Flowy",
  "Draped",
  "Tailored",
  "Maternity",
];
const brandEnums = [
  "Adidas",
  "Nike",
  "Puma",
  "Reebok",
  "Under Armour",
  "New Balance",
  "Asics",
  "Converse",
  "Vans",
  "Fila",
  "Skechers",
  "Salomon",
  "Merrell",
  "Brooks",
  "Hoka One One",
  "Altra",
  "On",
  "Saucony",
  "Mizuno",
  "Karhu",
  "La Sportiva",
  "Inov-8",
  "Topo Athletic",
  "John Lobb",
  "Arc'teryx",
  "Icebug",
  "Scarpa",
  "Dynafit",
  "Salming",
  "Vibram",
  "Lems",
  "Xero Shoes",
  "Luna Sandals",
  "Bedrock Sandals",
  "Earth Runners",
  "Shamma Sandals",
  "Unshoes",
  "Vivobarefoot",
  "Preety Little Thing",
  "Zeap",
  "Other",
];
const clothSizeEnums = [
  "Custom",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "XXL",
  "XXXL",
  "XXXXL",
  "2",
  "4",
  "6",
  "8",
  "10",
  "12",
  "14",
  "16",
  "18",
  "20",
  "22",
  "24",
  "26",
  "28",
  "30",
];
const shoeStyleEnums = [
  "Sneakers",
  "Boots",
  "Sandals",
  "Slippers",
  "Shoes",
  "Heels",
  "Flats",
  "Loafers",
  "Sliders",
  "Brogues",
];
const heelHightEnums = [
  `Ultra High Heel (4"+)`,
  `High Heel (3-4")`,
  `Mid Heel (2-3")`,
  `Low Heel (1-2")`,
  `Flat (0-1")`,
];
const heelTypeEnums = [
  "Block",
  "Cone",
  "Kitten",
  "Platform",
  "Stiletto",
  "Wedge",
  "Sport",
  "Novelty",
  "Other",
];
const shoeSizeEnums = [
  "Custom",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
];

const accessoryTypeEnums = [
  "Jewelry",
  "Bag",
  "Hat",
  "Scarf",
  "Gloves",
  "Belt",
  "Sunglasses",
  "Watch",
  "Hair Accessories",
  "Other",
];
const accessoryStyleEnums = [
  "Shoulder Bags",
  "Tote Bags",
  "Square Sunglasses",
  "Headband",
  "Statement Earings",
  "Choker Necklaces",
  "Corset Belt",
  "Ring",
  "Hair Clips",
  "Bucket Hats",
  "Crossbody Bags",
  "Clutch Bags",
  "Satchel Bags",
  "Backpacks",
  "Duffle Bags",
  "Bowler Bags",
  "Hobo Bags",
  "Messenger Bags",
  "Fanny Packs",
  "Socks",
  "Handbags",
  "Visor Sunglasses",
  "Aviator Sunglasses",
  "Round Sunglasses",
  "Tights",
  "Hoop Earings",
  "Stud Earings",
  "Dangle Earings",
  "Bracelets",
  "Rings",
  "Watches",
  "Anklets",
  "Necklaces",
  "Pendants",
  "Brooches",
  "Cufflinks",
  "Ties",
  "Bow Ties",
  "Scarves",
  "Shawls",
  "Pashminas",
  "Bandanas",
  "Gloves",
  "Mittens",
  "Beanies",
  "Berets",
  "Fedora Hats",
  "Trilby Hats",
  "Baseball Caps",
  "Snapback Caps",
  "Beanie Hats",
  "Bucket Hats",
  "Fedoras",
  "Panama Hats",
  "Boater Hats",
  "Cowboy Hats",
  "Cross Body Bags",
  "Scrunchie",
  "Cap",
];
const accessorySizeEnums = [
  "Standard",
  "Oversized",
  "Mini",
  "Micro Mini",
  "Large",
  "One Size",
];

const genderEnums = ["Male", "Female"];
const ageGroupEnums = ["Adults", "Kids"];
const ageRangeEnums = ["0-3", "4-7", "8-12", "13-17"];
const shoeTypeEnums = [
  "Sneakers",
  "Boots",
  "Sandals",
  "Slippers",
  "Shoes",
  "Heels",
  "Flats",
  "Loafers",
  "Sliders",
  "Brogues",
];
const productTypeEnums = [
  "readyMadeCloth",
  "readyMadeShoe",
  "accessory",
  "bespokeCloth",
  "bespokeShoe",
];

const bodyMeasurementEnums = [
  {
    name: "top",
    fields: [
      "Burst",
      "Shoulder",
      "Round off Shoulder",
      "Shoulder to Burst",
      "Shoulder to Waist",
      "Shoulder to Hips at Back",
      "Shoulder to Nipple",
      "Shoulder to Under Burst",
      "Nipple to Nipple",
      "Arm Length",
      "Arm Hole",
      "Strap",
      "Blouse Length",
      "Bicep",
      "Wrist",
      "Neck",
      "Back",
      "Front",
      "Bicep",
      "Wrist",
      "Neck",
      "Back",
      "Front",
      "Length",
      "Short Sleeve",
      "Long Sleeve",
      "Chest",
      "Under Burst",
      "3/4 Top",
    ],
  },
  {
    name: "trouser",
    fields: [
      "Waist",
      "Hips",
      "Thigh",
      "Knee",
      "Calf",
      "Ankle",
      "Inseam",
      "Outseam",
      "Rise",
      "Length",
      "3/4 Length",
      "Foot",
    ],
  },
  {
    name: "short",
    fields: [
      "Waist",
      "Hips",
      "Thigh",
      "Knee",
      "Calf",
      "Inseam",
      "Outseam",
      "Rise",
      "Length",
      "3/4 Length",
    ],
  },
  {
    name: "skirt",
    fields: [
      "Waist",
      "Hips",
      "Thigh",
      "Knee",
      "Inseam",
      "Outseam",
      "Rise",
      "Short",
      "Regular",
      "Half Length",
      "Full Length",
      "Foot",
    ],
  },
  {
    name: "dress",
    fields: [
      "Burst",
      "Waist",
      "Hips",
      "Shoulder",
      "Round off Shoulder",
      "Shoulder to Burst",
      "Shoulder to Waist",
      "Shoulder to Hips at Back",
      "Shoulder to Nipple",
      "Shoulder to Under Burst",
      "Nipple to Nipple",
      "Arm Length",
      "Arm Hole",
      "Strap",
      "Blouse Length",
      "Bicep",
      "Wrist",
      "Neck",
      "Back",
      "Front",
      "Full Length",
      "Half Length",
      "Short Sleeve",
      "Long Sleeve",
      "Chest",
      "Under Burst",
      "Under Hips",
      "3/4 Length",
      "Thigh",
      "Knee",
      "Calf",
      "Ankle",
      "Inseam",
      "Outseam",
      "Rise",
      "Foot",
    ],
  },
  {
    name: "jacket",
    fields: [
      "Burst",
      "Waist",
      "Hips",
      "Shoulder",
      "Round off Shoulder",
      "Arm Length",
      "Arm Hole",
      "Bicep",
      "Wrist",
      "Neck",
      "Back",
      "Front",
      "Length",
      "Short Sleeve",
      "Long Sleeve",
      "Chest",
      "Under Burst",
      "3/4 Top",
    ],
  },
  {
    name: "suit",
    fields: [
      "Burst",
      "Waist",
      "Hips",
      "Shoulder",
      "Round off Shoulder",
      "Arm Length",
      "Arm Hole",
      "Bicep",
      "Wrist",
      "Neck",
      "Back",
      "Front",
      "Length",
      "Short Sleeve",
      "Strap",
      "Blouse Length",
      "Long Sleeve",
      "Chest",
      "Under Burst",
      "3/4 Top",
    ],
  },
  {
    name: "shoe",
    fields: [
      "Length",
      "Width",
      "Height",
      "Calf",
      "Ankle",
      "Inseam",
      "Outseam",
      "Rise",
      "Foot",
    ],
  },
  {
    name: "hat",
    fields: ["Head Circumference", "Height", "Brim"],
  },
  {
    name: "african agbada",
    fields: ["Back to Wrist", "Neck to Wrist", "Full Length", "cap"],
  },
];

const statusEnums = ["draft", "live", "under review", "rejected", "deleted"];
const promoStatusEnums = ["draft", "live", "expired", "scheduled"];
const orderStatusEnums = [
  {
    name: "placed",
    value: "order placed",
  },
  {
    name: "confirmed",
    value: "order confirmed",
    sellerAction: true,
  },
  {
    name: "processing",
    value: "order processing",
    sellerAction: true,
  },
  {
    name: "ready",
    value: "order ready for delivery",
    sellerAction: true,
  },
  {
    name: "dispatched",
    value: "order dispatched",
  },
  {
    name: "delivered",
    value: "order delivered",
  },
  {
    name: "cancelled",
    value: "order cancelled",
  },
];
const nairaToOtherCurrencyEnums = {
  USD: 0.00065,
  GBP: 0.00051,
};
const currencyEnums = ["NGN", "USD", "GBP"];
const userVariables = ["firstName", "lastName", "email", "phoneNumber"];
const shopVariables = ["shopName"];
const orderVariables = ["orderId", "orderPoints"];

const searchQueryAllowedPaths = [{ label: "title", value: "title" },
  {
    path: "design",
    value: "categories.design"
  },
  {
    path: "occasion",
    value: "categories.occasion"
  },
  {
    path: "sleeveLength",
    value: "categories.sleeveLength"
  },
  {
    path: "style",
    value: "categories.style"
  },
 

];
module.exports = {
  genderEnums,
  ageGroupEnums,
  ageRangeEnums,
  shoeTypeEnums,
  productTypeEnums,
  statusEnums,
  sleeveLengthEnums,
  fasteningEnums,
  occasionEnums,
  fitEnums,
  brandEnums,
  colorEnums,
  clothStyleEnums,
  designEnums,
  clothSizeEnums,
  mainEnums,
  shoeStyleEnums,
  heelHightEnums,
  heelTypeEnums,
  shoeSizeEnums,
  accessoryTypeEnums,
  accessoryStyleEnums,
  accessorySizeEnums,
  promoStatusEnums,
  orderStatusEnums,
  nairaToOtherCurrencyEnums,
  currencyEnums,
  userVariables,
  shopVariables,
  orderVariables,
  searchQueryAllowedPaths
};
