const clothStyleEnums = [
  "2-in-1 Short",
  "A-Line Dress",
  "African Traditional",
  "Agbada",
  "Baby Tee",
  "Babban Riga",
  "Biker Jacket",
  "Bikini",
  "Blazer",
  "Blazer Dress",
  "Blouse",
  "Body Suit",
  "Bodycon Dress",
  "Bodyshort",
  "Boiler Suit",
  "Bralet",
  "Burkini",
  "Cape",
  "Capri",
  "Cardigan",
  "Catsuit",
  "Chino",
  "Coat",
  "Corset",
  "Corset Dress",
  "Coverall",
  "Crop Top",
  "Culotte",
  "Danshiki",
  "Dry Suit",
  "Dungaree",
  "Flare",
  "Gilet",
  "Halter",
  "Halter Top",
  "Harem Pant",
  "Hoodie",
  "Hot Pant",
  "Isi-Agu",
  "Jacket",
  "Jean",
  "Jegging",
  "Jogger",
  "Jumper",
  "Jumper Dress",
  "Jumpsuit",
  "Kaftan",
  "Kimono",
  "Knicker",
  "Legging",
  "Leotard",
  "Lingerie",
  "Matching Set",
  "Maxi Skirt",
  "Midaxi Skirt",
  "Mini Skirt",
  "Monokini",
  "Nightie",
  "Overall",
  "Oversized Jumper Dress",
  "Oversized T-Shirt",
  "Palazzo Pant",
  "Pant",
  "Parka",
  "Pea Coat",
  "Peplum",
  "Pencil Skirt",
  "Playsuit",
  "Polo",
  "Poncho",
  "Pullover",
  "Puffer Jacket",
  "Pyjama",
  "Rash Guard",
  "Romper",
  "Senator Suit",
  "Shift Dress",
  "Shirt",
  "Shirt Dress",
  "Short",
  "Shrug",
  "Skirt",
  "Slip Dress",
  "Street",
  "Suit",
  "Sweater",
  "Sweatshirt",
  "Swimsuit",
  "Tank Top",
  "Tankini",
  "Three Piece",
  "Thong",
  "Top & Jacket",
  "Top & Short",
  "Top & Skirt",
  "Top & Trouser",
  "Track Suit",
  "Trikini",
  "Trouser",
  "Tube Top",
  "Tunic",
  "Turtleneck",
  "Two Piece",
  "Tight",
  "T-Shirt",
  "Unitard",
  "Vest",
  "Vintage",
  "Waistcoat",
  "Wet Suit",
  "Wide Leg Trouser",
  "Windbreaker",
  "Work",
  "Other",
];

const onlyFemaleClothStyleEnums = [
  "A-Line Dress",
  "Ankara Gown",
  "Ankara Skirt and Blouse",
  "Aso-Oke",
  "Bikini",
  "Blazer Dress",
  "Blouse",
  "Body Suit",
  "Bodycon Dress",
  "Bralet",
  "Bubu/Boubou",
  "Burkini",
  "Cocktail Dress",
  "Corset",
  "Corset Dress",
  "Dress",
  "Halter Dress",
  "Halter Top",
  "Iro and Buba",
  "Jumper Dress",
  "Komole",
  "Legging",
  "Lingerie",
  "Maxi Dress",
  "Monokini",
  "Nightie",
  "Peplum",
  "Playsuit",
  "Shift Dress",
  "Sheath Dress",
  "Shirt Dress",
  "Short",
  "Skirt",
  "Slip Dress",
  "Sundress",
  "Swimsuit",
  "Tank Top",
  "Tankini",
  "Thong",
  "Three Piece",
  "Top & Jacket",
  "Top & Short",
  "Top & Skirt",
  "Top & Trouser",
  "Trikini",
  "Tunic",
  "Two Piece",
  "Waistcoat",
  "Wrap Dress",
];

const sleeveLengthEnums = [
  "Long Sleeve",
  "Short Sleeve",
  "Sleeveless",
  "Off Shoulder",
  "Strapless",
  "Spaghetti",
  "Cap Sleeve",
  "Puff Sleeve",
  "Bishop Sleeve",
  "Bell Sleeve",
  "Kimono Sleeve",
  "Dolman Sleeve",
  "Raglan Sleeve",
  "Batwing Sleeve",
  "Butterfly Sleeve",
  "Cold Shoulder",
  "One Shoulder",
  "Asymmetric",
  "Cape Sleeve",
  "Flounce Sleeve",
  "Ruffle Sleeve",
  "Tiered Sleeve",
];
const designEnums = [
  "Plain",
  "Faux Fur",
  "Ripped",
  "Buba",
  "Leather",
  "Patterned",
  "Printed",
  "Embroidered",
  "Sequined",
  "Lace",
  "Mesh",
  "Sheer",
  "Cut-Out",
  "Ruched",
  "Ruffled",
  "Tiered",
  "Pleated",
  "Frill",
  "Flounce",
  "Tie-Dye",
  "Tie-Front",
  "Wrap",
  "Twist",
  "Knot",
  "Bow",
  "Belted",
  "Buckle",
  "Buttoned",
  "Zipper",
  "Lace-Up",
  "Corset",
  "Peplum",
  "Puff",
  "Balloon",
  "Bubble",
  "Animal",
  "Leopard",
  "Check",
  "Plaid",
  "Tartan",
  "Striped",
  "Floral",
  "Tropical",
  "Paisley",
  "Geometric",
  "Abstract",
  "Aztec",
  "Tribal",
  "Camouflage",
  "Marble",
  "Rubber",
  "Metallic",
  "Reflective",
  "Iridescent",
  "Glitter",
  "Chain",
  "Studded",
  "Rhinestone",
  "Beaded",
  "Other",
];

const sizeStandardEnums = ["INTL", "UK", "US", "EU", "AUS", "CAN"];
const fasteningEnums = [
  "Belt",
  "Braid",
  "Buckle",
  "Button",
  "Clasp",
  "Cord",
  "Corset",
  "D-Ring",
  "Drawstring",
  "Elastic",
  "Frog",
  "Grommet",
  "Hook",
  "Knot",
  "Lace-Up",
  "Loop",
  "Magnet",
  "None",
  "Other",
  "Pleat",
  "Press-Stud",
  "Ribbon",
  "Rope",
  "Ruffle",
  "Sash",
  "Snap",
  "Tassel",
  "Tie",
  "Toggle",
  "Twist",
  "Velcro",
  "Wrap",
];
const fabricEnums = [
  "Cotton",
  "Polyester",
  "Nylon",
  "Spandex",
  "Rayon",
  "Linen",
  "Silk",
  "Wool",
  "Cashmere",
  "Leather",
  "Fur",
  "Faux Fur",
  "Denim",
  "Velvet",
  "Satin",
  "Chiffon",
  "Lace",
  "Mesh",
  "Sheer",
  "Tulle",
  "Knit",
  "Jersey",
  "Terry",
  "Fleece",
  "Flannel",
  "Tweed",
  "Corduroy",
  "Suede",
  "Sequin",
  "Glitter",
  "Metallic",
  "Lurex",
  "Lamé",
  "Brocade",
  "Jacquard",
  "Damask",
  "Taffeta",
];
const colorEnums = [
  { name: "Black", hex: "#000000" },
  { name: "White", hex: "#FFFFFF" },
  { name: "Red", hex: "#FF0000" },
  { name: "Burgundy", hex: "#800020" },
  { name: "Blue", hex: "#0000FF" },
  { name: "Green", hex: "#008000" },
  { name: "Yellow", hex: "#FFFF00" },
  { name: "Pink", hex: "#FFC0CB" },
  { name: "Purple", hex: "#800080" },
  { name: "Orange", hex: "#FFA500" },
  { name: "Brown", hex: "#A52A2A" },
  { name: "Grey", hex: "#808080" },
  { name: "Beige", hex: "#F5F5DC" },
  { name: "Navy", hex: "#000080" },
  { name: "Teal", hex: "#008080" },
  { name: "Turquoise", hex: "#40E0D0" },
  { name: "Mint", hex: "#98FF98" },
  { name: "Lime", hex: "#00FF00" },
  { name: "Olive", hex: "#808000" },
  { name: "Khaki", hex: "#F0E68C" },
  { name: "Gold", hex: "#FFD700" },
  { name: "Silver", hex: "#C0C0C0" },
  { name: "Bronze", hex: "#CD7F32" },
  { name: "Copper", hex: "#B87333" },
  { name: "Rose Gold", hex: "#B76E79" },
  { name: "Metallic", hex: "#D3AF37" },
  { name: "Neon", hex: "#39FF14" },
  { name: "Pastel", hex: "#FF6961" },
  { name: "Rainbow", hex: "#FF0000" },
  {
    name: "Multicolor",
    background:
      "radial-gradient(circle, hsla(41, 83%, 70%, 1) 23%, hsla(321, 90%, 70%, 1) 100%)",
  },
  { name: "Lilac", hex: "#C8A2C8" },
  { name: "Tan", hex: "#D2B48C" },
  { name: "Wine", hex: "#722F37" },
  { name: "Chocolate", hex: "#D2691E" },
  { name: "Milk", hex: "#F5F5DC" },
];
const mainEnums = [
  "Top",
  "Bottom",
  "Dress",
  "Matching Set",
  "Footwear",
  "Overall",
  "Accessories",
  "Cultural",
  "Suit",
  "Other",
];
const nonClothMainEnums = ["Footwear", "Accessories"];
const occasionEnums = [
  "Athletic",
  "Autumn",
  "Ballet",
  "Beach",
  "Boho",
  "Bridal",
  "Bridal Shower",
  "Bride",
  "Bridesmaid",
  "Business",
  "Camping",
  "Casual",
  "Chic",
  "Cocktail",
  "Corporate",
  "Cruise",
  "Cultural",
  "Cycling",
  "Dance",
  "Day",
  "Date",
  "Dressy",
  "Evening",
  "Fall",
  "Festive",
  "Fitness",
  "Formal",
  "Funeral",
  "Gala",
  "Gym",
  "Gymnastics",
  "Groom",
  "Groomsman",
  "Hiking",
  "Holiday",
  "Horse Riding",
  "Maternity",
  "Office",
  "Other",
  "Outdoor",
  "Party",
  "Pilates",
  "Retro",
  "Resort",
  "Running",
  "Scootering",
  "Sexy",
  "Skateboarding",
  "Skating",
  "Skiing",
  "Smart Casual",
  "Spring",
  "Sports",
  "Summer",
  "Surfing",
  "Swimming",
  "Travel",
  "Vacation",
  "Walking",
  "Wedding",
  "Winter",
  "Work",
];

const fitEnums = [
  "Regular",
  "Slim",
  "Skinny",
  "Straight",
  "Bootcut",
  "Flare",
  "Wide-Leg",
  "Cropped",
  "Culotte",
  "Palazzo",
  "Paperbag",
  "Pegged",
  "Tapered",
  "Carrot",
  "Boyfriend",
  "Mom",
  "Dad",
  "High-Waist",
  "Low-Waist",
  "Mid-Waist",
  "Drop-Waist",
  "Plus-Size",
  "Petite",
  "Maternity",
  "Tall",
  "Short",
  "Long",
  "Oversized",
  "Fitted",
  "Relaxed",
  "Baggy",
  "Slouchy",
  "Boxy",
  "Flowy",
  "Draped",
  "Tailored",
  "Other",
];
const brandEnums = [
  "Adidas",
  "Nike",
  "Puma",
  "Reebok",
  "Under Armour",
  "New Balance",
  "Asics",
  "Converse",
  "Vans",
  "Fila",
  "Skechers",
  "Salomon",
  "Merrell",
  "Brooks",
  "Hoka One One",
  "Altra",
  "On",
  "Saucony",
  "Mizuno",
  "Karhu",
  "La Sportiva",
  "Inov-8",
  "Topo Athletic",
  "John Lobb",
  "Arc'teryx",
  "Icebug",
  "Scarpa",
  "Dynafit",
  "Salming",
  "Vibram",
  "Lems",
  "Xero Shoes",
  "Luna Sandals",
  "Bedrock Sandals",
  "Earth Runners",
  "Shamma Sandals",
  "Unshoes",
  "Vivobarefoot",
  "Preety Little Thing",
  "Zeaper",
  "Zara",
  "Boohoo",
  "H&M",
  "Forever 21",
  "ASOS",
  "Mango",
  "Topshop",
  "Topman",
  "Tommy Hilfiger",
  "Calvin Klein",
  "Levi's",
  "Wrangler",
  "Lee",
  "Gucci",
  "Other",
];

const clothSizeEnumsByRegion = {
  US: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "18",
    "20",
    "22",
    "24",
    "32",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
    "48",
  ],
  UK: [
    "2",
    "4",
    "6",
    "8",
    "10",
    "12",
    "14",
    "16",
    "18",
    "20",
    "22",
    "24",
    "26",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
  ],
  EU: [
    "32",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
    "48",
    "50",
    "52",
    "54",
    "56",
  ],
  AUS: [
    "4",
    "6",
    "8",
    "10",
    "12",
    "14",
    "16",
    "18",
    "20",
    "22",
    "24",
    "26",
    "28",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
  ],
  CAN: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "18",
    "20",
    "22",
    "24",
    "32",
    "34",
    "36",
    "38",
    "40",
    "42",
    "44",
    "46",
    "48",
  ],
  INTL: [
    "4XL",
    "5XL",
    "L",
    "M",
    "One Size",
    "Petite",
    "Plus Size",
    "S",
    "Tall",
    "XL",
    "XS",
    "XXL",
    "XXS",
    "XXXL",
    "XXXS",
    "Custom"
  ],
};

// Combine, deduplicate, and sort
const clothSizeEnums = Array.from(
  new Set(
    Object.values(clothSizeEnumsByRegion).flat().map(String) // ensure all are strings
  )
).sort((a, b) => {
  const numA = Number(a);
  const numB = Number(b);

  // numeric sort first, then alphabetic
  if (!isNaN(numA) && !isNaN(numB)) return numA - numB;
  if (!isNaN(numA)) return -1; // numbers come before text
  if (!isNaN(numB)) return 1;
  return a.localeCompare(b);
});

const shoeStyleEnums = [
  "Sneakers",
  "Boots",
  "Sandals",
  "Slippers",
  "Shoes",
  "Heels",
  "Other",
  "Flats",
  "Loafers",
  "Sliders",
  "Brogues",
];
const heelHightEnums = [
  `Ultra High Heel (4"+)`,
  `High Heel (3-4")`,
  `Mid Heel (2-3")`,
  `Low Heel (1-2")`,
  `Flat (0-1")`,
];
const heelTypeEnums = [
  "Block",
  "Cone",
  "Kitten",
  "Platform",
  "Stiletto",
  "Wedge",
  "Sport",
  "Novelty",
  "Other",
];

const shoeSizeEnumsByRegion = {
  US: [
    "4",
    "4.5",
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "11.5",
    "12",
    "12.5",
    "13",
    "14",
    "15",
  ],
  UK: [
    "3",
    "3.5",
    "4",
    "4.5",
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "12",
    "13",
    "14",
  ],
  EU: [
    "35",
    "35.5",
    "36",
    "36.5",
    "37",
    "37.5",
    "38",
    "38.5",
    "39",
    "39.5",
    "40",
    "40.5",
    "41",
    "42",
    "42.5",
    "43",
    "44",
    "45",
    "45.5",
    "46",
    "47",
  ],
  AUS: [
    "3",
    "3.5",
    "4",
    "4.5",
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "12",
    "13",
    "14",
  ],
  CAN: [
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "11.5",
    "12",
    "12.5",
    "13",
    "14",
    "15",
  ],
  CM: [
    "22",
    "22.5",
    "23",
    "23.5",
    "24",
    "24.5",
    "25",
    "25.5",
    "26",
    "26.5",
    "27",
    "27.5",
    "28",
    "28.5",
    "29",
    "29.5",
    "30",
  ],
  INTL: ["XS", "S", "M", "L", "XL", "XXL", "XXXL", "One Size", "Adjustable", "Custom"],
};

// Combine, deduplicate, and sort
const shoeSizeEnums = Array.from(
  new Set(
    Object.values(shoeSizeEnumsByRegion).flat().map(String) // ensure all are strings
  )
).sort((a, b) => {
  const numA = Number(a);
  const numB = Number(b);

  // numeric sort first, then alphabetic
  if (!isNaN(numA) && !isNaN(numB)) return numA - numB;
  if (!isNaN(numA)) return -1;
  if (!isNaN(numB)) return 1;
  return a.localeCompare(b);
});

const accessoryTypeEnums = [
  "Jewelry",
  "Bag",
  "Hat",
  "Scarf",
  "Gloves",
  "Belt",
  "Sunglasses",
  "Watch",
  "Hair Accessories",
  "Makeup",
  "Socks",
  "Fragrance",
  "Skin Care",
  "Other",
];
const accessoryStyleEnums = [
  "Anklets",
  "Aviator Sunglasses",
  "Backpacks",
  "Bandanas",
  "Baseball Caps",
  "Beanies",
  "Berets",
  "Belts",
  "Blazers",
  "Boater Hats",
  "Bow Ties",
  "Bowler Bags",
  "Bracelets",
  "Brooches",
  "Bucket Hats",
  "Bustier",
  "Camisoles",
  "Cap",
  "Caps",
  "Choker Necklaces",
  "Clutch Bags",
  "Corset Belt",
  "Cowboy Hats",
  "Crossbody Bags",
  "Cross Body Bags",
  "Cufflinks",
  "Dangle Earrings",
  "Duffle Bags",
  "Earrings",
  "Fanny Packs",
  "Fedora Hats",
  "Fedoras",
  "Gele",
  "Gloves",
  "Hair Accessories",
  "Hair Clips",
  "Handbags",
  "Hat",
  "Headband",
  "Hobo Bags",
  "Hoop Earrings",
  "Hosiery",
  "Lapel Pins",
  "Messenger Bags",
  "Mittens",
  "Necklaces",
  "Other",
  "Panama Hats",
  "Pashminas",
  "Pendants",
  "Pocket Squares",
  "Rings",
  "Round Sunglasses",
  "Satchel Bags",
  "Scarves",
  "Scrunchie",
  "Shawls",
  "Shoulder Bags",
  "Socks",
  "Square Sunglasses",
  "Statement Earrings",
  "Stud Earrings",
  "Sunglasses",
  "Suspenders",
  "Teddy",
  "Tie Clips",
  "Ties",
  "Tights",
  "Tote Bags",
  "Trilby Hats",
  "Visor Sunglasses",
  "Wallets/Card Holders",
  "Watches",
];
const onlyFemaleAccessoryStyleEnums = [
  "Anklets",
  "Bandanas",
  "Beanies",
  "Brooches",
  "Bustier",
  "Choker Necklaces",
  "Clutch Bags",
  "Corset Belt",
  "Cross Body Bags",
  "Dangle Earrings",
  "Fanny Packs",
  "Gele",
  "Hair Accessories",
  "Hair Clips",
  "Handbags",
  "Headband",
  "Hoop Earrings",
  "Pashminas",
  "Scrunchie",
  "Shawls",
  "Statement Earrings",
  "Stud Earrings",
  "Teddy",
  "Tote Bags",
];

const onlyMaleAccessoryStyleEnums = [
  "Bow Ties",
  "Cufflinks",
  "Pocket Squares",
  "Suspenders",
  "Tie Bars",
  "Tie Clips",
  "Ties",
  "Waistcoat Chains",
];

const accessorySizeEnums = [
  "Standard",
  "Oversized",
  "Mini",
  "Micro Mini",
  "Large",
  "One Size",
  "Adjustable",
  "Other",
];

const genderEnums = ["Male", "Female"];
const ageGroupEnums = ["Adults", "Kids"];
const ageRangeEnums = ["0-3", "4-7", "8-12", "13-17"];
const shoeTypeEnums = [
  "Sneakers",
  "Boots",
  "Sandals",
  "Slippers",
  "Shoes",
  "Heels",
  "Flats",
  "Loafers",
  "Sliders",
  "Brogues",
];
const productTypeEnums = [
  "readyMadeCloth",
  "readyMadeShoe",
  "accessory",
  "bespokeCloth",
  "bespokeShoe",
];

// const bodyMeasurementEnums = [
//   {
//     name: "top",
//     fields: [
//       "Burst",
//       "Shoulder",
//       "Round off Shoulder",
//       "Shoulder to Burst",
//       "Shoulder to Waist",
//       "Shoulder to Hips at Back",
//       "Shoulder to Nipple",
//       "Shoulder to Under Burst",
//       "Nipple to Nipple",
//       "Arm Length",
//       "Arm Hole",
//       "Strap",
//       "Blouse Length",
//       "Bicep",
//       "Wrist",
//       "Neck",
//       "Back",
//       "Front",
//       "Bicep",
//       "Wrist",
//       "Neck",
//       "Back",
//       "Front",
//       "Length",
//       "Short Sleeve",
//       "Long Sleeve",
//       "Chest",
//       "Under Burst",
//       "3/4 Top",
//     ],
//   },
//   {
//     name: "trouser",
//     fields: [
//       "Waist",
//       "Hips",
//       "Thigh",
//       "Knee",
//       "Calf",
//       "Ankle",
//       "Inseam",
//       "Outseam",
//       "Rise",
//       "Length",
//       "3/4 Length",
//       "Foot",
//     ],
//   },
//   {
//     name: "short",
//     fields: [
//       "Waist",
//       "Hips",
//       "Thigh",
//       "Knee",
//       "Calf",
//       "Inseam",
//       "Outseam",
//       "Rise",
//       "Length",
//       "3/4 Length",
//     ],
//   },
//   {
//     name: "skirt",
//     fields: [
//       "Waist",
//       "Hips",
//       "Thigh",
//       "Knee",
//       "Inseam",
//       "Outseam",
//       "Rise",
//       "Short",
//       "Regular",
//       "Half Length",
//       "Full Length",
//       "Foot",
//     ],
//   },
//   {
//     name: "dress",
//     fields: [
//       "Burst",
//       "Waist",
//       "Hips",
//       "Shoulder",
//       "Round off Shoulder",
//       "Shoulder to Burst",
//       "Shoulder to Waist",
//       "Shoulder to Hips at Back",
//       "Shoulder to Nipple",
//       "Shoulder to Under Burst",
//       "Nipple to Nipple",
//       "Arm Length",
//       "Arm Hole",
//       "Strap",
//       "Blouse Length",
//       "Bicep",
//       "Wrist",
//       "Neck",
//       "Back",
//       "Front",
//       "Full Length",
//       "Half Length",
//       "Short Sleeve",
//       "Long Sleeve",
//       "Chest",
//       "Under Burst",
//       "Under Hips",
//       "3/4 Length",
//       "Thigh",
//       "Knee",
//       "Calf",
//       "Ankle",
//       "Inseam",
//       "Outseam",
//       "Rise",
//       "Foot",
//     ],
//   },
//   {
//     name: "jacket",
//     fields: [
//       "Burst",
//       "Waist",
//       "Hips",
//       "Shoulder",
//       "Round off Shoulder",
//       "Arm Length",
//       "Arm Hole",
//       "Bicep",
//       "Wrist",
//       "Neck",
//       "Back",
//       "Front",
//       "Length",
//       "Short Sleeve",
//       "Long Sleeve",
//       "Chest",
//       "Under Burst",
//       "3/4 Top",
//     ],
//   },
//   {
//     name: "suit",
//     fields: [
//       "Burst",
//       "Waist",
//       "Hips",
//       "Shoulder",
//       "Round off Shoulder",
//       "Arm Length",
//       "Arm Hole",
//       "Bicep",
//       "Wrist",
//       "Neck",
//       "Back",
//       "Front",
//       "Length",
//       "Short Sleeve",
//       "Strap",
//       "Blouse Length",
//       "Long Sleeve",
//       "Chest",
//       "Under Burst",
//       "3/4 Top",
//     ],
//   },
//   {
//     name: "shoe",
//     fields: [
//       "Length",
//       "Width",
//       "Height",
//       "Calf",
//       "Ankle",
//       "Inseam",
//       "Outseam",
//       "Rise",
//       "Foot",
//     ],
//   },
//   {
//     name: "hat",
//     fields: ["Head Circumference", "Height", "Brim"],
//   },
//   {
//     name: "african agbada",
//     fields: ["Back to Wrist", "Neck to Wrist", "Full Length", "cap"],
//   },
// ];

const statusEnums = ["draft", "live", "under review", "rejected", "deleted"];
const promoStatusEnums = ["draft", "live", "expired", "scheduled"];
const orderStatusEnums = [
  {
    name: "placed",
    value: "order placed",
    percentage: 0,
  },
  {
    name: "confirmed",
    value: "order confirmed",
    sellerAction: true,
    percentage: 20,
  },
  {
    name: "processing",
    value: "order processing",
    sellerAction: true,
    percentage: 40,
  },
  {
    name: "ready for delivery",
    value: "order ready for delivery",
    sellerAction: true,
    percentage: 60,
  },
  {
    name: "dispatched",
    value: "order dispatched",
    percentage: 80,
  },
  {
    name: "delivered",
    value: "order delivered",
    percentage: 100,
  },
  {
    name: "cancelled",
    value: "order cancelled",
    percentage: 0,
  },
];
const nairaToOtherCurrencyEnums = {
  USD: 0.00065,
  GBP: 0.00051,
};
const currencyEnums = ["NGN", "USD", "GBP"];
const userVariables = ["firstName", "lastName", "email", "phoneNumber"];
const shopVariables = ["shopName"];
const orderVariables = ["orderId", "orderPoints", "itemNo"];
const productOrderVariables = [
  "orderId",
  "orderPoints",
  "itemNo",
  "productTitle",
  "productQuantity",
  "expectedVendorCompletionDate",
  "sku",
];

const searchQueryAllowedPaths = [
  { path: "title", value: "title" },
  {
    path: "design",
    value: "categories.design",
  },
  {
    path: "occasion",
    value: "categories.occasion",
  },
  {
    path: "sleeveLength",
    value: "categories.sleeveLength",
  },
  {
    path: "style",
    value: "categories.style",
  },
];
const allowedDeliveryCountries = [
  "Nigeria",
  "United States",
  "United Kingdom",
  "Canada",
];
const helpCenterCategoryEnums = ["customer", "vendor", "account"];
const helpCenterSubCategoryEnums = [
  "beforeOrdering",
  "checkoutAndPayment",
  "deliveryAndShipping",
  "returnsAndRefunds",
  "authentication",
  "myListings",
  "payments",
  "ratings",
  "loginAndSecurity",
  "notifications",
  "privacy",
  "support",
];
const ZeaperPolicy = "https://admin.zeaper.com/docs/Zeaper_Policy.pdf";
const vendorContract =
  "https://admin.zeaper.com/docs/Zeap_vendor_contract.v2.pdf";
const notificationTypeEnums = [
  "general",
  "order",
  "promo",
  "account",
  "system",
  "voucher",
  "point",
  "review",
  "product",
  "shop",
];
const roleTypeEnums = ["buyer", "vendor", "admin"];
const onboardingDocumentEnums = [
  {
    slug: "proof_of_identity",
    label: "Proof of Identity",
    hint: "International Passport, Driver's Licence, Voter's Card.",
  },
  {
    slug: "business_registration",
    label: "Business Registration Document",
    hint: "CAC certificate, incorporation docs, etc.",
  },
  {
    slug: "business_address",
    label: "Proof of Business Address",
    hint: "Utility bill, bank statement (≤ 3 months).",
  },
];
module.exports = {
  genderEnums,
  ageGroupEnums,
  ageRangeEnums,
  shoeTypeEnums,
  productTypeEnums,
  statusEnums,
  sleeveLengthEnums,
  fasteningEnums,
  occasionEnums,
  fitEnums,
  brandEnums,
  colorEnums,
  clothStyleEnums,
  onlyFemaleClothStyleEnums,
  designEnums,
  clothSizeEnums,
  clothSizeEnumsByRegion,
  mainEnums,
  nonClothMainEnums,
  shoeStyleEnums,
  heelHightEnums,
  sizeStandardEnums,
  heelTypeEnums,
  shoeSizeEnums,
  shoeSizeEnumsByRegion,
  accessoryTypeEnums,
  accessoryStyleEnums,
  onlyMaleAccessoryStyleEnums,
  onlyFemaleAccessoryStyleEnums,
  accessorySizeEnums,
  promoStatusEnums,
  orderStatusEnums,
  nairaToOtherCurrencyEnums,
  currencyEnums,
  userVariables,
  shopVariables,
  orderVariables,
  productOrderVariables,
  searchQueryAllowedPaths,
  allowedDeliveryCountries,
  helpCenterCategoryEnums,
  helpCenterSubCategoryEnums,
  fabricEnums,
  // bodyMeasurementEnums,
  ZeaperPolicy,
  vendorContract,
  notificationTypeEnums,
  roleTypeEnums,
  onboardingDocumentEnums,
};
