const femaleSizeGuide = {
  top: {
    inch: [
      {
        Size: "XS",
        "US/CAN": "0/1",
        UK: "2/4",
        EU: "32/34",
        AUS: "4/6",
        Bust: "32-33",
        Waist: "24-25",
        Hips: "35-36",
      },
      {
        Size: "S",
        "US/CAN": "3/5",
        UK: "6/8",
        EU: "36/38",
        AUS: "8",
        Bust: "34-35",
        Waist: "26-27",
        Hips: "37-38",
      },
      {
        Size: "M",
        "US/CAN": "7/9",
        UK: "10/12",
        EU: "40",
        AUS: "10/12",
        Bust: "36-37",
        Waist: "28-29",
        Hips: "39-40",
      },
      {
        Size: "L",
        "US/CAN": "11/13",
        UK: "14",
        EU: "42",
        AUS: "14/16",
        Bust: "38.5-40",
        Waist: "30.5-32",
        Hips: "41.5-43",
      },
      {
        Size: "XL",
        "US/CAN": "15",
        UK: "16",
        EU: "44",
        AUS: "18",
        Bust: "41 1/2",
        Waist: "33 1/2",
        Hips: "44 1/2",
      },
      {
        Size: "XXL",
        "US/CAN": "14/16",
        UK: "18",
        EU: "44/46",
        AUS: "18/20",
        Bust: "44-45.5",
        Waist: "37-38.5",
        Hips: "47-48.5",
      },
      {
        Size: "XXXL",
        "US/CAN": "18/20",
        UK: "20/22",
        EU: "48/50",
        AUS: "22/24",
        Bust: "47-49",
        Waist: "40-42",
        Hips: "50-52",
      },
      {
        Size: "XXXXL",
        "US/CAN": "22/24",
        UK: "24/26",
        EU: "52/54",
        AUS: "26/28",
        Bust: "51-53",
        Waist: "44-46",
        Hips: "54-56",
      },
    ],
    cm: [
      {
        Size: "XS",
        UK: "2/4",
        EU: "32/34",
        AUS: "4/6",
        "US/CAN": "0/1",
        Bust: "81-84",
        Waist: "61-64",
        Hips: "89-91",
      },
      {
        Size: "S",
        UK: "6/8",
        EU: "36/38",
        AUS: "8",
        "US/CAN": "3/5",
        Bust: "86-89",
        Waist: "66-69",
        Hips: "94-97",
      },
      {
        Size: "M",
        UK: "10/12",
        EU: "40",
        AUS: "10/12",
        "US/CAN": "7/9",
        Bust: "91-94",
        Waist: "71-74",
        Hips: "99-102",
      },
      {
        Size: "L",
        UK: "14",
        EU: "42",
        AUS: "14/16",
        "US/CAN": "11/13",
        Bust: "98-102",
        Waist: "77-81",
        Hips: "105-109",
      },
      {
        Size: "XL",
        UK: "16",
        EU: "44",
        AUS: "18",
        "US/CAN": "15",
        Bust: "105",
        Waist: "85",
        Hips: "113",
      },
      {
        Size: "XXL",
        UK: "18",
        EU: "44/46",
        AUS: "18/20",
        "US/CAN": "14/16",
        Bust: "112-115.5",
        Waist: "94-98.5",
        Hips: "119-123.5",
      },
      {
        Size: "XXXL",
        UK: "20/22",
        EU: "48/50",
        AUS: "22/24",
        "US/CAN": "18/20",
        Bust: "119-124",
        Waist: "102-107",
        Hips: "127-132",
      },
      {
        Size: "XXXXL",
        UK: "24/26",
        EU: "52/54",
        AUS: "26/28",
        "US/CAN": "22/24",
        Bust: "129.5-134.5 ",
        Waist: "111.5-116.5 ",
        Hips: "137-142 ",
      },
    ],
  },
  bottom: {
    inch: [
      {
        Size: "XS",
        UK: "2/4",
        EU: "32/34",
        AUS: "4/6",
        "US/CAN": "0/1",
        Waist: "24-25",
        Hips: "35-36",
      },
      {
        Size: "S",
        "US/CAN": "3/5",
        UK: "6/8",
        EU: "36/38",
        AUS: "8",
        Waist: "26-27",
        Hips: "37-38",
      },
      {
        Size: "M",
        "US/CAN": "7/9",
        UK: "10/12",
        EU: "40",
        AUS: "10/12",
        Waist: "28-29",
        Hips: "39-40",
      },
      {
        Size: "L",

        "US/CAN": "11/13",
        UK: "14",
        EU: "42",
        AUS: "14/16",
        Waist: "30.5-32",
        Hips: "41.5-43",
      },
      {
        Size: "XL",
        "US/CAN": "15",
        UK: "16",
        EU: "44",
        AUS: "18",
        Waist: "33 1/2",
        Hips: "44 1/2",
      },
      {
        Size: "XXL",
        "US/CAN": "14/16",
        UK: "18",
        EU: "44/46",
        AUS: "18/20",
        Waist: "37-38.5",
        Hips: "47-48.5",
      },
      {
        Size: "XXXL",
        "US/CAN": "18/20",
        UK: "20/22",
        EU: "48/50",
        AUS: "22/24",
        Waist: "40-42",
        Hips: "50-52",
      },
      {
        Size: "XXXXL",
        "US/CAN": "22/24",
        UK: "24/26",
        EU: "52/54",
        AUS: "26/28",
        Waist: "44-46",
        Hips: "54-56",
      },
    ],
    cm: [
      {
        Size: "XS",
        UK: "2/4",
        EU: "32/34",
        AUS: "4/6",
        "US/CAN": "0/1",
        Waist: "61-64",
        Hips: "89-91",
      },
      {
        Size: "S",
        UK: "6/8",
        EU: "36/38",
        AUS: "8",
        "US/CAN": "3/5",
        Waist: "66-69",
        Hips: "94-97",
      },
      {
        Size: "M",
        UK: "10/12",
        EU: "40",
        AUS: "10/12",
        "US/CAN": "7/9",
        Waist: "71-74",
        Hips: "99-102",
      },
      {
        Size: "L",
        UK: "14",
        EU: "42",
        AUS: "14/16",
        "US/CAN": "11/13",
        Waist: "77-81",
        Hips: "105-109",
      },
      {
        Size: "XL",
        UK: "16",
        EU: "44",
        AUS: "18",
        "US/CAN": "15",
        Waist: "85",
        Hips: "113",
      },
      {
        Size: "XXL",
        UK: "18 ",
        EU: "44/46 ",
        AUS: "18/20 ",
        "US/CAN": "14/16",
        Waist: "94-98.5 ",
        Hips: "119-123.5 ",
      },
      {
        Size: "XXXL",
        UK: "20/22 ",
        EU: "48/50 ",
        AUS: "22/24 ",
        "US/CAN": "18/20",
        Waist: "102-107 ",
        Hips: "127-132 ",
      },
      {
        Size: "XXXXL",
        UK: "24/26 ",
        EU: "52/54 ",
        AUS: "26/28 ",
        "US/CAN": "22/24",
        Waist: "111.5-116.5 ",
        Hips: "137-142 ",
      },
    ],
  },
  footwear: {
    inch: [
      {
        Size: "5",
        "US/CAN": "5",
        UK: "3",
        EU: "35-36",
        AUS: "5",
        "Foot Length": "8.7",
      },
      {
        Size: "5.5",
        "US/CAN": "5.5",
        UK: "3.5",
        EU: "36",
        AUS: "5.5",
        "Foot Length": "8.9",
      },
      {
        Size: "6",
        "US/CAN": "6",
        UK: "4",
        EU: "36-37",
        AUS: "6",
        "Foot Length": "9.1",
      },
      {
        Size: "6.5",
        "US/CAN": "6.5",
        UK: "4.5",
        EU: "37",
        AUS: "6.5",
        "Foot Length": "9.3",
      },
      {
        Size: "7",
        "US/CAN": "7",
        UK: "5",
        EU: "37-38",
        AUS: "7",
        "Foot Length": "9.5",
      },
      {
        Size: "7.5",
        "US/CAN": "7.5",
        UK: "5.5",
        EU: "38",
        AUS: "7.5",
        "Foot Length": "9.7",
      },
      {
        Size: "8",
        "US/CAN": "8",
        UK: "6",
        EU: "38 - 39",
        AUS: "8",
        "Foot Length": "9.9",
      },
      {
        Size: "8.5",
        "US/CAN": "8.5",
        UK: "6.5",
        EU: "39",
        AUS: "8.5",
        "Foot Length": "10.1",
      },
      {
        Size: "9",
        "US/CAN": "9",
        UK: "7",
        EU: "40",
        AUS: "9",
        "Foot Length": "10.3",
      },
      {
        Size: "10",
        "US/CAN": "10",
        UK: "8",
        EU: "41",
        AUS: "10",
        "Foot Length": "10.5",
      },
      {
        Size: "11",
        "US/CAN": "11",
        UK: "9",
        EU: "42",
        AUS: "11",
        "Foot Length": "10.9",
      },
    ],
    cm: [
      {
        Size: "5",
        "US/CAN": "5",
        UK: "3",
        EU: "35-36",
        AUS: "5",
        "Foot Length": "22.1",
      },
      {
        Size: "5.5",
        "US/CAN": "5.5",
        UK: "3.5",
        EU: "36",
        AUS: "5.5",
        "Foot Length": "22.6",
      },
      {
        Size: "6",
        "US/CAN": "6",
        UK: "4",
        EU: "36-37",
        AUS: "6",
        "Foot Length": "23.1",
      },
      {
        Size: "6.5",
        "US/CAN": "6.5",
        UK: "4.5",
        EU: "37",
        AUS: "6.5",
        "Foot Length": "23.6",
      },
      {
        Size: "7",
        "US/CAN": "7",
        UK: "5",
        EU: "37-38",
        AUS: "7",
        "Foot Length": "24.1",
      },
      {
        Size: "7.5",
        "US/CAN": "7.5",
        UK: "5.5",
        EU: "38",
        AUS: "7.5",
        "Foot Length": "24.6",
      },
      {
        Size: "8",
        "US/CAN": "8",
        UK: "6",
        EU: "38 - 39",
        AUS: "8",
        "Foot Length": "25.1",
      },
      {
        Size: "8.5",
        "US/CAN": "8.5",
        UK: "6.5",
        EU: "39",
        AUS: "8.5",
        "Foot Length": "25.6",
      },
      {
        Size: "9",
        "US/CAN": "9",
        UK: "7",
        EU: "40",
        AUS: "9",
        "Foot Length": "26.1",
      },
      {
        Size: "10",
        "US/CAN": "10",
        UK: "8",
        EU: "41",
        AUS: "10",
        "Foot Length": "",
      },
      {
        Size: "11",
        "US/CAN": "11",
        UK: "9",
        EU: "42",
        AUS: "11",
        "Foot Length": "27.7",
      },
    ],
  },
};
const maleSizeGuide = {
  top: {
    inch: [
      {
        Size: "XS",
        Chest: "32-34",
        "US/CAN": "32-34",
        UK: "34",
        EU: "44",
        AUS: "34",
      },
      {
        Size: "S",
        Chest: "35-37",
        "US/CAN": "34-36",
        UK: "36",
        EU: "46",
        AUS: "36",
      },
      {
        Size: "M",
        Chest: "38-40",
        "US/CAN": "38-40",
        UK: "38",
        EU: "48",
        AUS: "38",
      },
      {
        Size: "L",
        Chest: "42-44",
        "US/CAN": "40-42",
        UK: "40",
        EU: "50",
        AUS: "40",
      },
      {
        Size: "XL",
        Chest: "46-48",
        "US/CAN": "44-46",
        UK: "42",
        EU: "52",
        AUS: "42",
      },
      {
        Size: "XXL",
        Chest: "50-52",
        "US/CAN": "44-46",
        UK: "44",
        EU: "54",
        AUS: "44",
      },
      {
        Size: "XXXL",
        Chest: "54-56",
        "US/CAN": "46-48",
        UK: "46",
        EU: "56",
        AUS: "46",
      },
    ],
    cm: [
      {
        Size: "XS",
        Chest: "81-86",
        "US/CAN": "32-34",
        UK: "34",
        EU: "44",
        AUS: "34",
      },
      {
        Size: "S",
        Chest: "88.9-94",
        "US/CAN": "34-36",
        UK: "36",
        EU: "46",
        AUS: "36",
      },
      {
        Size: "M",
        Chest: "96.5-101.6",
        "US/CAN": "38-40",
        UK: "38",
        EU: "48",
        AUS: "38",
      },
      {
        Size: "L",
        Chest: "106.7-111.8",
        "US/CAN": "40-42",
        UK: "40",
        EU: "50",
        AUS: "40",
      },
      {
        Size: "XL",
        Chest: "116.8-121.9",

        "US/CAN": "44-46",
        UK: "42",
        EU: "52",
        AUS: "42",
      },
      {
        Size: "XXL",
        Chest: "127-132.1",

        "US/CAN": "44-46",
        UK: "44",
        EU: "54",
        AUS: "44",
      },
      {
        Size: "XXXL",
        Chest: "137.2-142.2",
        "US/CAN": "46-48",
        UK: "46",
        EU: "56",
        AUS: "46",
      },
    ],
  },
  bottom: {
    inch: [
      {
        Size: "XXS",
        Waist: "28",
        Hips: "31.5",
        "US/CAN": "28",
        UK: "28",
        EU: "44",
        AUS: "28",
      },
      {
        Size: "XS",
        Waist: "30",
        Hips: "33.5",
        "US/CAN": "30",
        UK: "30",
        EU: "46",
        AUS: "30",
      },
      {
        Size: "S",
        Waist: "32",
        Hips: "35.5",
        "US/CAN": "32",
        UK: "32",
        EU: "48",
        AUS: "32",
      },
      {
        Size: "M",
        Waist: "34",
        Hips: "37.5",
        "US/CAN": "34",
        UK: "34",
        EU: "50",
        AUS: "34",
      },
      {
        Size: "L",
        Waist: "37",
        Hips: "39.5",
        "US/CAN": "36",
        UK: "36",
        EU: "52",
        AUS: "36",
      },
      {
        Size: "XL",
        Waist: "39.5",
        Hips: "41.5",
        "US/CAN": "38",
        UK: "38",
        EU: "54",
      },
      {
        Size: "XXL",
        Waist: "42",
        Hips: "43.5",
        "US/CAN": "40",
        UK: "40",
        EU: "56",
        AUS: "40",
      },
      {
        Size: "XXXL",
        Waist: "44.5",
        Hips: "45.5",
        "US/CAN": "42",
        UK: "42",
        EU: "58",
        AUS: "42",
      },
      {
        Size: "XXXXL",
        Waist: "47",
        Hips: "47.5",
        "US/CAN": "44",
        UK: "44",
        EU: "60",
        AUS: "44",
      },
    ],
    cm: [
      {
        Size: "XXS",
        Waist: "71",
        Hips: "80",
        UK: "28",
        EU: "44",
        AUS: "28",
        "US/CAN": "28",
      },
      {
        Size: "XS",
        Waist: "76",
        Hips: "85",
        UK: "30",
        EU: "46",
        AUS: "30",
        "US/CAN": "30",
      },
      {
        Size: "S",
        Waist: "81",
        Hips: "90",
        UK: "32",
        EU: "48",
        AUS: "32",
        "US/CAN": "32",
      },
      {
        Size: "M",
        Waist: "86.5",
        Hips: "95.5",
        UK: "34",
        EU: "50",
        AUS: "34",
        "US/CAN": "34",
      },
      {
        Size: "L",
        Waist: "93",
        Hips: "100",
        UK: "36",
        EU: "52",
        AUS: "36",
        "US/CAN": "36",
      },
      {
        Size: "XL",
        Waist: "100",
        Hips: "105",
        UK: "38",
        EU: "54",
        AUS: "38",
        "US/CAN": "38",
      },
      {
        Size: "XXL",
        Waist: "107",
        Hips: "110",
        UK: "40",
        EU: "56",
        AUS: "40",
        "US/CAN": "40",
      },
      {
        Size: "XXXL",
        Waist: "113",
        Hips: "115",
        UK: "42",
        EU: "58",
        AUS: "42",
        "US/CAN": "42",
      },
      {
        Size: "XXXXL",
        Waist: "117",
        Hips: "120",
        UK: "44",
        EU: "60",
        AUS: "44",
        "US/CAN": "44",
      },
    ],
  },
  footwear: {
    inch: [
      {
        Size: "5",
        "US/CAN": "5",
        UK: "4",
        EU: "37",
        AUS: "4",
        "Foot Length": "9.1",
      },
      {
        Size: "6",
        "US/CAN": "6",
        UK: "5",
        EU: "38",
        AUS: "5",
        "Foot Length": "9.5",
      },
      {
        Size: "7",
        "US/CAN": "7",
        UK: "6",
        EU: "40",
        AUS: "6",
        "Foot Length": "9.7",
      },
      {
        Size: "8",
        "US/CAN": "8",
        UK: "7",
        EU: "41",
        AUS: "7",
        "Foot Length": "10.1",
      },
      {
        Size: "9",
        "US/CAN": "9",
        UK: "8",
        EU: "42.5",
        AUS: "8",
        "Foot Length": "10.5",
      },
      {
        Size: "10",
        "US/CAN": "10",
        UK: "9",
        EU: "44",
        AUS: "9",
        "Foot Length": "11.0",
      },
      {
        Size: "11",
        "US/CAN": "11",
        UK: "10",
        EU: "45.5",
        AUS: "10",
        "Foot Length": "11.3",
      },
      {
        Size: "12",
        "US/CAN": "12",
        UK: "11",
        EU: "47",
        AUS: "11",
        "Foot Length": "11.7",
      },
    ],
    cm: [
      {
        Size: "5",
        "US/CAN": "5",
        UK: "4",
        EU: "37",
        AUS: "4",
        "Foot Length": "23.1",
      },
      {
        Size: "6",
        "US/CAN": "6",
        UK: "5",
        EU: "38",
        AUS: "5",
        "Foot Length": "24.1",
      },
      {
        Size: "7",
        "US/CAN": "7",
        UK: "6",
        EU: "40",
        AUS: "6",
        "Foot Length": "24.6",
      },
      {
        Size: "8",
        "US/CAN": "8",
        UK: "7",
        EU: "41",
        AUS: "7",
        "Foot Length": "25.6",
      },
      {
        Size: "9",
        "US/CAN": "9",
        UK: "8",
        EU: "42.5",
        AUS: "8",
        "Foot Length": "26.7",
      },
      {
        Size: "10",
        "US/CAN": "10",
        UK: "9",
        EU: "44",
        AUS: "9",
        "Foot Length": "27.9",
      },
      {
        Size: "11",
        "US/CAN": "11",
        UK: "10",
        EU: "45.5",
        AUS: "10",
        "Foot Length": "28.7",
      },
      {
        Size: "12",
        "US/CAN": "12",
        UK: "11",
        EU: "47",
        AUS: "11",
        "Foot Length": "29.6",
      },
    ],
  },
};

const readyMadeSizeGuide = {
  female: femaleSizeGuide,
  male: maleSizeGuide,
};
module.exports = readyMadeSizeGuide;
